using Relay.CLI.Commands;
using Relay.CLI.Migration;
using Xunit;

namespace Relay.CLI.Tests.Commands;

public class MigrationReportGeneratorTests : IDisposable
{
    private readonly string _tempDir;

    public MigrationReportGeneratorTests()
    {
        _tempDir = Path.Combine(Path.GetTempPath(), $"relay-report-tests-{Guid.NewGuid()}");
        Directory.CreateDirectory(_tempDir);
    }

    [Fact]
    public async Task SaveMigrationReport_WithJsonFormat_ShouldGenerateJsonFile()
    {
        // Arrange
        var result = CreateTestMigrationResult();
        var outputPath = Path.Combine(_tempDir, "report.json");

        // Act
        await MigrationReportGenerator.SaveMigrationReport(result, outputPath, "json");

        // Assert
        Assert.True(File.Exists(outputPath));
        var content = await File.ReadAllTextAsync(outputPath);
        Assert.Contains("\"Status\":", content);
        Assert.Contains("\"FilesModified\":", content);
        Assert.Contains("\"Changes\":", content);
    }

    [Fact]
    public async Task SaveMigrationReport_WithHtmlFormat_ShouldGenerateHtmlFile()
    {
        // Arrange
        var result = CreateTestMigrationResult();
        var outputPath = Path.Combine(_tempDir, "report.html");

        // Act
        await MigrationReportGenerator.SaveMigrationReport(result, outputPath, "html");

        // Assert
        Assert.True(File.Exists(outputPath));
        var content = await File.ReadAllTextAsync(outputPath);
        Assert.Contains("<!DOCTYPE html>", content);
        Assert.Contains("<title>Migration Report</title>", content);
        Assert.Contains("🔄 Migration Report", content);
    }

    [Fact]
    public async Task SaveMigrationReport_WithMarkdownFormat_ShouldGenerateMarkdownFile()
    {
        // Arrange
        var result = CreateTestMigrationResult();
        var outputPath = Path.Combine(_tempDir, "report.md");

        // Act
        await MigrationReportGenerator.SaveMigrationReport(result, outputPath, "markdown");

        // Assert
        Assert.True(File.Exists(outputPath));
        var content = await File.ReadAllTextAsync(outputPath);
        Assert.Contains("# Migration Report", content);
        Assert.Contains("| Metric | Value |", content);
    }

    [Fact]
    public async Task SaveMigrationReport_WithUnknownFormat_ShouldDefaultToMarkdown()
    {
        // Arrange
        var result = CreateTestMigrationResult();
        var outputPath = Path.Combine(_tempDir, "report.unknown");

        // Act
        await MigrationReportGenerator.SaveMigrationReport(result, outputPath, "unknown");

        // Assert
        Assert.True(File.Exists(outputPath));
        var content = await File.ReadAllTextAsync(outputPath);
        Assert.Contains("# Migration Report", content);
    }

    [Fact]
    public async Task GenerateJsonReport_ShouldSerializeMigrationResult()
    {
        // Arrange
        var result = CreateTestMigrationResult();
        var outputPath = Path.Combine(_tempDir, "test.json");

        // Act
        await MigrationReportGenerator.SaveMigrationReport(result, outputPath, "json");
        var json = await File.ReadAllTextAsync(outputPath);

        // Assert
        Assert.Contains("\"Status\":", json);
        Assert.Contains("\"FilesModified\":", json);
        Assert.Contains("\"Changes\":", json);
        Assert.Contains("\"ManualSteps\":", json);
        Assert.Contains("\"CreatedBackup\":", json);
        Assert.Contains("\"BackupPath\":", json);
    }

    [Fact]
    public async Task SaveMigrationReport_WithMarkdownFormatAndBasicResult_ShouldGenerateCompleteReport()
    {
        // Arrange
        var result = new MigrationResult
        {
            Status = MigrationStatus.Success,
            Duration = TimeSpan.FromSeconds(5.5),
            FilesModified = 10,
            LinesChanged = 150,
            HandlersMigrated = 8,
            CreatedBackup = false,
            Changes = new(),
            ManualSteps = new()
        };
        var outputPath = Path.Combine(_tempDir, "basic.md");

        // Act
        await MigrationReportGenerator.SaveMigrationReport(result, outputPath, "markdown");
        var markdown = await File.ReadAllTextAsync(outputPath);

        // Assert
        Assert.Contains("# Migration Report", markdown);
        Assert.Contains("**Status:** Success", markdown);
        Assert.Contains("**Duration:** 5.50s", markdown);
        Assert.Contains("| Files Modified | 10 |", markdown);
        Assert.Contains("| Lines Changed | 150 |", markdown);
        Assert.Contains("| Handlers Migrated | 8 |", markdown);
        Assert.Contains("*Generated by Relay CLI Migration Tool*", markdown);
    }

    [Fact]
    public async Task SaveMigrationReport_WithMarkdownFormatAndChanges_ShouldGroupByCategoryAndShowIcons()
    {
        // Arrange
        var result = new MigrationResult
        {
            Status = MigrationStatus.Success,
            Duration = TimeSpan.FromSeconds(1.0),
            FilesModified = 1,
            LinesChanged = 10,
            HandlersMigrated = 1,
            CreatedBackup = false,
            Changes =
            [
                new() { Category = "Using Directives", Type = ChangeType.Remove, Description = "Removed MediatR using" },
                new() { Category = "Using Directives", Type = ChangeType.Add, Description = "Added Relay.Core using" },
                new() { Category = "Package References", Type = ChangeType.Modify, Description = "Updated MediatR to Relay.Core" }
            ],
            ManualSteps = new()
        };
        var outputPath = Path.Combine(_tempDir, "changes.md");

        // Act
        await MigrationReportGenerator.SaveMigrationReport(result, outputPath, "markdown");
        var markdown = await File.ReadAllTextAsync(outputPath);

        // Assert
        Assert.Contains("## Changes Applied", markdown);
        Assert.Contains("### Using Directives", markdown);
        Assert.Contains("### Package References", markdown);
        Assert.Contains("- ➖ Removed MediatR using", markdown);
        Assert.Contains("- ➕ Added Relay.Core using", markdown);
        Assert.Contains("- ✏️ Updated MediatR to Relay.Core", markdown);
    }

    [Fact]
    public async Task SaveMigrationReport_WithMarkdownFormatAndManualSteps_ShouldListSteps()
    {
        // Arrange
        var result = new MigrationResult
        {
            Status = MigrationStatus.Success,
            Duration = TimeSpan.FromSeconds(1.0),
            FilesModified = 1,
            LinesChanged = 10,
            HandlersMigrated = 1,
            CreatedBackup = false,
            Changes = new(),
            ManualSteps = ["Step 1: Update configuration", "Step 2: Test the application"]
        };
        var outputPath = Path.Combine(_tempDir, "manual.md");

        // Act
        await MigrationReportGenerator.SaveMigrationReport(result, outputPath, "markdown");
        var markdown = await File.ReadAllTextAsync(outputPath);

        // Assert
        Assert.Contains("## Manual Steps Required", markdown);
        Assert.Contains("1. Step 1: Update configuration", markdown);
        Assert.Contains("2. Step 2: Test the application", markdown);
    }

    [Fact]
    public async Task SaveMigrationReport_WithMarkdownFormatAndBackup_ShouldShowBackupInfo()
    {
        // Arrange
        var result = new MigrationResult
        {
            Status = MigrationStatus.Success,
            Duration = TimeSpan.FromSeconds(1.0),
            FilesModified = 1,
            LinesChanged = 10,
            HandlersMigrated = 1,
            CreatedBackup = true,
            BackupPath = "C:\\backup\\test",
            Changes = new(),
            ManualSteps = new()
        };
        var outputPath = Path.Combine(_tempDir, "backup.md");

        // Act
        await MigrationReportGenerator.SaveMigrationReport(result, outputPath, "markdown");
        var markdown = await File.ReadAllTextAsync(outputPath);

        // Assert
        Assert.Contains("## Backup Information", markdown);
        Assert.Contains("**Backup Path:** `C:\\backup\\test`", markdown);
        Assert.Contains("relay migrate rollback --backup C:\\backup\\test", markdown);
    }

    [Fact]
    public async Task SaveMigrationReport_WithMarkdownFormatAndNoBackup_ShouldNotShowBackupSection()
    {
        // Arrange
        var result = new MigrationResult
        {
            Status = MigrationStatus.Success,
            Duration = TimeSpan.FromSeconds(1.0),
            FilesModified = 1,
            LinesChanged = 10,
            HandlersMigrated = 1,
            CreatedBackup = false,
            Changes = new(),
            ManualSteps = new()
        };
        var outputPath = Path.Combine(_tempDir, "nobackup.md");

        // Act
        await MigrationReportGenerator.SaveMigrationReport(result, outputPath, "markdown");
        var markdown = await File.ReadAllTextAsync(outputPath);

        // Assert
        Assert.DoesNotContain("## Backup Information", markdown);
        Assert.DoesNotContain("Backup Path", markdown);
    }

    [Fact]
    public async Task SaveMigrationReport_WithHtmlFormatAndSuccessStatus_ShouldUseGreenColorAndCheckmark()
    {
        // Arrange
        var result = new MigrationResult
        {
            Status = MigrationStatus.Success,
            Duration = TimeSpan.FromSeconds(1.0),
            FilesModified = 1,
            LinesChanged = 10,
            HandlersMigrated = 1,
            CreatedBackup = false,
            Changes = new(),
            ManualSteps = new()
        };
        var outputPath = Path.Combine(_tempDir, "success.html");

        // Act
        await MigrationReportGenerator.SaveMigrationReport(result, outputPath, "html");
        var html = await File.ReadAllTextAsync(outputPath);

        // Assert
        Assert.Contains("background: #4CAF50", html);
        Assert.Contains("✅ Success", html);
        Assert.Contains("🔄 Migration Report", html);
        Assert.Contains("<!DOCTYPE html>", html);
    }

    [Fact]
    public async Task SaveMigrationReport_WithHtmlFormatAndPartialStatus_ShouldUseYellowColorAndWarning()
    {
        // Arrange
        var result = new MigrationResult
        {
            Status = MigrationStatus.Partial,
            Duration = TimeSpan.FromSeconds(1.0),
            FilesModified = 1,
            LinesChanged = 10,
            HandlersMigrated = 1,
            CreatedBackup = false,
            Changes = new(),
            ManualSteps = new()
        };
        var outputPath = Path.Combine(_tempDir, "partial.html");

        // Act
        await MigrationReportGenerator.SaveMigrationReport(result, outputPath, "html");
        var html = await File.ReadAllTextAsync(outputPath);

        // Assert
        Assert.Contains("background: #FFC107", html);
        Assert.Contains("⚠️ Partial", html);
    }

    [Fact]
    public async Task SaveMigrationReport_WithHtmlFormatAndFailedStatus_ShouldUseRedColorAndCross()
    {
        // Arrange
        var result = new MigrationResult
        {
            Status = MigrationStatus.Failed,
            Duration = TimeSpan.FromSeconds(1.0),
            FilesModified = 1,
            LinesChanged = 10,
            HandlersMigrated = 1,
            CreatedBackup = false,
            Changes = new(),
            ManualSteps = new()
        };
        var outputPath = Path.Combine(_tempDir, "failed.html");

        // Act
        await MigrationReportGenerator.SaveMigrationReport(result, outputPath, "html");
        var html = await File.ReadAllTextAsync(outputPath);

        // Assert
        Assert.Contains("background: #F44336", html);
        Assert.Contains("❌ Failed", html);
    }

    [Fact]
    public async Task SaveMigrationReport_WithHtmlFormatAndChanges_ShouldShowChangesWithColorsAndIcons()
    {
        // Arrange
        var result = new MigrationResult
        {
            Status = MigrationStatus.Success,
            Duration = TimeSpan.FromSeconds(1.0),
            FilesModified = 1,
            LinesChanged = 10,
            HandlersMigrated = 1,
            CreatedBackup = false,
            Changes =
            [
                new() { Category = "Using Directives", Type = ChangeType.Add, Description = "Added Relay.Core using" },
                new() { Category = "Package References", Type = ChangeType.Remove, Description = "Removed MediatR package" },
                new() { Category = "Package References", Type = ChangeType.Modify, Description = "Updated version" }
            ],
            ManualSteps = new()
        };
        var outputPath = Path.Combine(_tempDir, "changes.html");

        // Act
        await MigrationReportGenerator.SaveMigrationReport(result, outputPath, "html");
        var html = await File.ReadAllTextAsync(outputPath);

        // Assert
        Assert.Contains("📝 Changes Applied", html);
        Assert.Contains("change-add", html);
        Assert.Contains("change-remove", html);
        Assert.Contains("change-modify", html);
        Assert.Contains("<span class='icon-add'>➕</span>", html);
        Assert.Contains("<span class='icon-remove'>➖</span>", html);
        Assert.Contains("<span class='icon-modify'>✏️</span>", html);
    }

    [Fact]
    public async Task SaveMigrationReport_WithHtmlFormatAndManualSteps_ShouldShowManualStepsSection()
    {
        // Arrange
        var result = new MigrationResult
        {
            Status = MigrationStatus.Success,
            Duration = TimeSpan.FromSeconds(1.0),
            FilesModified = 1,
            LinesChanged = 10,
            HandlersMigrated = 1,
            CreatedBackup = false,
            Changes = new(),
            ManualSteps = ["Step 1: Update configuration", "Step 2: Test the application"]
        };
        var outputPath = Path.Combine(_tempDir, "manual.html");

        // Act
        await MigrationReportGenerator.SaveMigrationReport(result, outputPath, "html");
        var html = await File.ReadAllTextAsync(outputPath);

        // Assert
        Assert.Contains("⚠️ Manual Steps Required", html);
        Assert.Contains("manual-steps", html);
        Assert.Contains("<li>Step 1: Update configuration</li>", html);
        Assert.Contains("<li>Step 2: Test the application</li>", html);
    }

    [Fact]
    public async Task SaveMigrationReport_WithHtmlFormatAndBackup_ShouldShowBackupSection()
    {
        // Arrange
        var result = new MigrationResult
        {
            Status = MigrationStatus.Success,
            Duration = TimeSpan.FromSeconds(1.0),
            FilesModified = 1,
            LinesChanged = 10,
            HandlersMigrated = 1,
            CreatedBackup = true,
            BackupPath = "C:\\backup\\test",
            Changes = new(),
            ManualSteps = new()
        };
        var outputPath = Path.Combine(_tempDir, "backup.html");

        // Act
        await MigrationReportGenerator.SaveMigrationReport(result, outputPath, "html");
        var html = await File.ReadAllTextAsync(outputPath);

        // Assert
        Assert.Contains("💾 Backup Information", html);
        Assert.Contains("backup-info", html);
        Assert.Contains("<code>C:\\backup\\test</code>", html);
        Assert.Contains("relay migrate rollback --backup C:\\backup\\test", html);
    }

    [Fact]
    public async Task SaveMigrationReport_WithHtmlFormatAndNullBackupPath_ShouldNotShowBackupSection()
    {
        // Arrange
        var result = new MigrationResult
        {
            Status = MigrationStatus.Success,
            Duration = TimeSpan.FromSeconds(1.0),
            FilesModified = 1,
            LinesChanged = 10,
            HandlersMigrated = 1,
            CreatedBackup = true,
            BackupPath = null,
            Changes = new(),
            ManualSteps = new()
        };
        var outputPath = Path.Combine(_tempDir, "nullbackup.html");

        // Act
        await MigrationReportGenerator.SaveMigrationReport(result, outputPath, "html");
        var html = await File.ReadAllTextAsync(outputPath);

        // Assert
        Assert.DoesNotContain("💾 Backup Information", html);
        Assert.DoesNotContain("Backup Path:", html);
    }

    [Fact]
    public async Task SaveMigrationReport_WithHtmlFormatAndEmptyBackupPath_ShouldNotShowBackupSection()
    {
        // Arrange
        var result = new MigrationResult
        {
            Status = MigrationStatus.Success,
            Duration = TimeSpan.FromSeconds(1.0),
            FilesModified = 1,
            LinesChanged = 10,
            HandlersMigrated = 1,
            CreatedBackup = true,
            BackupPath = "",
            Changes = new(),
            ManualSteps = new()
        };
        var outputPath = Path.Combine(_tempDir, "emptybackup.html");

        // Act
        await MigrationReportGenerator.SaveMigrationReport(result, outputPath, "html");
        var html = await File.ReadAllTextAsync(outputPath);

        // Assert
        Assert.DoesNotContain("💾 Backup Information", html);
        Assert.DoesNotContain("Backup Path:", html);
    }

    [Fact]
    public async Task SaveMigrationReport_WithHtmlFormatAndNoBackup_ShouldNotShowBackupSection()
    {
        // Arrange
        var result = new MigrationResult
        {
            Status = MigrationStatus.Success,
            Duration = TimeSpan.FromSeconds(1.0),
            FilesModified = 1,
            LinesChanged = 10,
            HandlersMigrated = 1,
            CreatedBackup = false,
            Changes = new(),
            ManualSteps = new()
        };
        var outputPath = Path.Combine(_tempDir, "nobackup.html");

        // Act
        await MigrationReportGenerator.SaveMigrationReport(result, outputPath, "html");
        var html = await File.ReadAllTextAsync(outputPath);

        // Assert
        Assert.DoesNotContain("💾 Backup Information", html);
        Assert.DoesNotContain("Backup Path:", html);
    }

    private static MigrationResult CreateTestMigrationResult()
    {
        return new MigrationResult
        {
            Status = MigrationStatus.Success,
            StartTime = DateTime.Now.AddSeconds(-5),
            EndTime = DateTime.Now,
            Duration = TimeSpan.FromSeconds(5),
            FilesModified = 10,
            LinesChanged = 150,
            HandlersMigrated = 8,
            CreatedBackup = true,
            BackupPath = "C:\\backup\\test",
            Changes =
            [
                new() { Category = "Using Directives", Type = ChangeType.Remove, Description = "Removed MediatR using" },
                new() { Category = "Using Directives", Type = ChangeType.Add, Description = "Added Relay.Core using" },
                new() { Category = "Package References", Type = ChangeType.Modify, Description = "Updated MediatR to Relay.Core" }
            ],
            ManualSteps = ["Step 1: Update configuration", "Step 2: Test the application"],
            Issues = new()
        };
    }

    public void Dispose()
    {
        try
        {
            if (Directory.Exists(_tempDir))
            {
                Directory.Delete(_tempDir, true);
            }
        }
        catch { }
    }
}