
using Relay.Core.Pipeline.Extensions;
using Relay.Core.Extensions;
using Relay.ControllerApiSample.Infrastructure;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container
builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(options =>
{
    options.SwaggerDoc("v1", new() {
        Title = "Relay Controller API Sample",
        Version = "v1",
        Description = "A controller-based API sample demonstrating Relay framework features"
    });
});

// Register InMemoryDatabase as singleton
builder.Services.AddSingleton<InMemoryDatabase>();

// Register all handlers and core Relay services (generated by source generator)
builder.Services.AddRelay();

// Add additional Relay features
// This includes: validation, pre/post processors, and exception handlers
builder.Services
    .AddRelayValidation()
    .AddRelayPrePostProcessors()
    .AddRelayExceptionHandlers();

var app = builder.Build();

// Configure the HTTP request pipeline
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();
app.UseAuthorization();
app.MapControllers();

app.Run();
