using System;
using Microsoft.Extensions.DependencyInjection;
using Relay.Core;
using Relay.Core.Configuration;

namespace Relay
{
    /// <summary>
    /// Extension methods for configuring the Relay framework.
    /// </summary>
    public static class ServiceCollectionExtensions
    {
        /// <summary>
        /// Adds Relay configuration services to the service collection.
        /// Note: The main AddRelay method is now generated by the source generator.
        /// </summary>
        /// <param name="services">The service collection to add services to.</param>
        /// <returns>The service collection for chaining.</returns>
        public static IServiceCollection AddRelayConfiguration(this IServiceCollection services)
        {
            if (services == null)
                throw new ArgumentNullException(nameof(services));

            // Add core Relay configuration (NOT calling AddRelayConfiguration recursively!)
            services.Configure<RelayOptions>(options => { }); // Register default options
            services.AddTransient<IRelay, RelayImplementation>();

            // Register default dispatchers (will be replaced by generated ones if available)
            services.AddTransient<IRequestDispatcher, FallbackRequestDispatcher>();
            services.AddTransient<IStreamDispatcher, StreamDispatcher>();
            services.AddTransient<INotificationDispatcher, NotificationDispatcher>();

            return services;
        }
    }
}