using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using System.Collections.Generic;
using System.Linq;
using Relay.SourceGenerator;
using Xunit;

namespace Relay.SourceGenerator.Tests;

public class OptimizedDispatcherGeneratorTests
{
    private RelayCompilationContext CreateTestContext()
    {
        var code = @"
namespace Test
{
    public class TestRequest : Relay.Core.IRequest<string> { }
    public class TestHandler
    {
        [Relay.Core.Attributes.Handle]
        public async System.Threading.Tasks.ValueTask<string> HandleAsync(TestRequest request, System.Threading.CancellationToken cancellationToken)
        {
            return ""test"";
        }
    }
}";

        var compilation = CreateCompilation(code);
        return new RelayCompilationContext(compilation, System.Threading.CancellationToken.None);
    }

    private Compilation CreateCompilation(string source)
    {
        var syntaxTree = CSharpSyntaxTree.ParseText(source);
        var references = AppDomain.CurrentDomain.GetAssemblies()
            .Where(a => !a.IsDynamic && !string.IsNullOrWhiteSpace(a.Location))
            .Select(a => MetadataReference.CreateFromFile(a.Location))
            .ToList();

        return CSharpCompilation.Create(
            "TestAssembly",
            new[] { syntaxTree },
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
    }

    private HandlerInfo CreateMockHandler(string requestType, string responseType, string handlerType = "TestHandler", string methodName = "HandleAsync", bool isStatic = false, string? handlerName = null, int priority = 0)
    {
        var compilation = CreateCompilation($@"
namespace Test {{
    public class {requestType} : Relay.Core.IRequest<{responseType}> {{ }}
    public class {handlerType} {{
        {(isStatic ? "public static" : "public")} async System.Threading.Tasks.ValueTask<{responseType}> {methodName}({requestType} request, System.Threading.CancellationToken cancellationToken) => default;
    }}
}}");

        var semanticModel = compilation.GetSemanticModel(compilation.SyntaxTrees.First());
        var requestTypeSymbol = semanticModel.Compilation.GetTypeByMetadataName($"Test.{requestType}");
        var responseTypeSymbol = semanticModel.Compilation.GetTypeByMetadataName($"Test.{responseType}");
        var handlerTypeSymbol = semanticModel.Compilation.GetTypeByMetadataName($"Test.{handlerType}");

        var methodSymbol = handlerTypeSymbol?.GetMembers(methodName).OfType<IMethodSymbol>().FirstOrDefault();

        var handler = new HandlerInfo
        {
            MethodSymbol = methodSymbol,
            HandlerTypeSymbol = handlerTypeSymbol,
            RequestTypeSymbol = requestTypeSymbol,
            ResponseTypeSymbol = responseTypeSymbol,
            Attributes = new List<RelayAttributeInfo>
            {
                new RelayAttributeInfo
                {
                    Type = RelayAttributeType.Handle,
                    AttributeData = CreateMockAttributeData(handlerName, priority)
                }
            }
        };

        return handler;
    }

    private AttributeData CreateMockAttributeData(string? handlerName, int priority)
    {
        // For testing purposes, we'll create a mock attribute data
        // In a real scenario, this would be created from actual syntax
        return null!;
    }

    [Fact]
    public void Constructor_ShouldThrowOnNullContext()
    {
        // Act & Assert
        var exception = Assert.Throws<ArgumentNullException>(() => new OptimizedDispatcherGenerator(null!));
        Assert.Equal("context", exception.ParamName);
    }

    [Fact]
    public void Constructor_ShouldInitializeWithContext()
    {
        // Arrange
        var context = CreateTestContext();

        // Act
        var generator = new OptimizedDispatcherGenerator(context);

        // Assert
        Assert.NotNull(generator);
    }

    [Fact]
    public void GenerateOptimizedDispatcher_ShouldGenerateHeaderComments()
    {
        // Arrange
        var context = CreateTestContext();
        var generator = new OptimizedDispatcherGenerator(context);
        var discoveryResult = new HandlerDiscoveryResult();

        // Act
        var source = generator.GenerateOptimizedDispatcher(discoveryResult);

        // Assert
        Assert.Contains("// <auto-generated />", source);
        Assert.Contains("// Generated by Relay.SourceGenerator - Optimized Dispatcher", source);
        Assert.Contains("// Generation time:", source);
    }

    [Fact]
    public void GenerateOptimizedDispatcher_ShouldIncludeRequiredUsings()
    {
        // Arrange
        var context = CreateTestContext();
        var generator = new OptimizedDispatcherGenerator(context);
        var discoveryResult = new HandlerDiscoveryResult();

        // Act
        var source = generator.GenerateOptimizedDispatcher(discoveryResult);

        // Assert
        Assert.Contains("using System;", source);
        Assert.Contains("using System.Collections.Generic;", source);
        Assert.Contains("using System.Runtime.CompilerServices;", source);
        Assert.Contains("using System.Threading;", source);
        Assert.Contains("using System.Threading.Tasks;", source);
        Assert.Contains("using Microsoft.Extensions.DependencyInjection;", source);
        Assert.Contains("using Relay.Core;", source);
    }

    [Fact]
    public void GenerateOptimizedDispatcher_ShouldGenerateOptimizedDispatcherClass()
    {
        // Arrange
        var context = CreateTestContext();
        var generator = new OptimizedDispatcherGenerator(context);
        var discoveryResult = new HandlerDiscoveryResult();

        // Act
        var source = generator.GenerateOptimizedDispatcher(discoveryResult);

        // Assert
        Assert.Contains("namespace Relay.Generated", source);
        Assert.Contains("public static class OptimizedDispatcher", source);
        Assert.Contains("High-performance dispatcher with specialized methods for each request type", source);
    }

    [Fact]
    public void GenerateOptimizedDispatcher_ShouldIncludeMethodImplAttribute()
    {
        // Arrange
        var context = CreateTestContext();
        var generator = new OptimizedDispatcherGenerator(context);
        var discoveryResult = new HandlerDiscoveryResult();

        // Act
        var source = generator.GenerateOptimizedDispatcher(discoveryResult);

        // Assert
        Assert.Contains("[MethodImpl(MethodImplOptions.AggressiveInlining)]", source);
    }

    [Fact]
    public void GenerateOptimizedDispatcher_WithEmptyHandlers_ShouldGenerateValidCode()
    {
        // Arrange
        var context = CreateTestContext();
        var generator = new OptimizedDispatcherGenerator(context);
        var discoveryResult = new HandlerDiscoveryResult();

        // Act
        var source = generator.GenerateOptimizedDispatcher(discoveryResult);

        // Assert
        Assert.False(string.IsNullOrWhiteSpace(source));
        Assert.Contains("public static class OptimizedDispatcher", source);
    }

    [Fact]
    public void GenerateOptimizedDispatcher_ShouldGenerateBasicStructure()
    {
        // Arrange
        var context = CreateTestContext();
        var generator = new OptimizedDispatcherGenerator(context);
        var discoveryResult = new HandlerDiscoveryResult();

        // Act
        var source = generator.GenerateOptimizedDispatcher(discoveryResult);
        var syntaxTree = CSharpSyntaxTree.ParseText(source);

        // Assert - With empty handlers, the generated code structure should still be syntactically correct
        // (though it may not compile due to missing references)
        Assert.NotNull(syntaxTree);
        Assert.Contains("public static class OptimizedDispatcher", source);
    }

    [Fact]
    public void GenerateOptimizedDispatcher_ShouldIncludeNamespace()
    {
        // Arrange
        var context = CreateTestContext();
        var generator = new OptimizedDispatcherGenerator(context);
        var discoveryResult = new HandlerDiscoveryResult();

        // Act
        var source = generator.GenerateOptimizedDispatcher(discoveryResult);

        // Assert
        Assert.Contains("namespace Relay.Generated", source);
    }

    [Fact]
    public void GenerateOptimizedDispatcher_ShouldHaveProperIndentation()
    {
        // Arrange
        var context = CreateTestContext();
        var generator = new OptimizedDispatcherGenerator(context);
        var discoveryResult = new HandlerDiscoveryResult();

        // Act
        var source = generator.GenerateOptimizedDispatcher(discoveryResult);

        // Assert
        Assert.Contains("    public static class OptimizedDispatcher", source);
        Assert.DoesNotContain("\t", source); // Should use spaces, not tabs
    }

    [Fact]
    public void GenerateOptimizedDispatcher_ShouldIncludeXmlDocumentation()
    {
        // Arrange
        var context = CreateTestContext();
        var generator = new OptimizedDispatcherGenerator(context);
        var discoveryResult = new HandlerDiscoveryResult();

        // Act
        var source = generator.GenerateOptimizedDispatcher(discoveryResult);

        // Assert
        Assert.Contains("/// <summary>", source);
        Assert.Contains("/// </summary>", source);
    }

    [Fact]
    public void GenerateOptimizedDispatcher_ShouldGenerateUTCTimestamp()
    {
        // Arrange
        var context = CreateTestContext();
        var generator = new OptimizedDispatcherGenerator(context);
        var discoveryResult = new HandlerDiscoveryResult();
        var beforeGeneration = DateTime.UtcNow;

        // Act
        var source = generator.GenerateOptimizedDispatcher(discoveryResult);

        // Assert
        Assert.Matches(@"// Generation time: \d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2} UTC", source);
    }

    [Fact]
    public void GenerateOptimizedDispatcher_ShouldHandleMultipleGenerationCalls()
    {
        // Arrange
        var context = CreateTestContext();
        var generator = new OptimizedDispatcherGenerator(context);
        var discoveryResult = new HandlerDiscoveryResult();

        // Act
        var source1 = generator.GenerateOptimizedDispatcher(discoveryResult);
        var source2 = generator.GenerateOptimizedDispatcher(discoveryResult);

        // Assert - Both should be valid (timestamps may differ)
        Assert.False(string.IsNullOrWhiteSpace(source1));
        Assert.False(string.IsNullOrWhiteSpace(source2));
        Assert.Contains("public static class OptimizedDispatcher", source1);
        Assert.Contains("public static class OptimizedDispatcher", source2);
    }

    [Fact]
    public void GenerateOptimizedDispatcher_ShouldUseStaticClass()
    {
        // Arrange
        var context = CreateTestContext();
        var generator = new OptimizedDispatcherGenerator(context);
        var discoveryResult = new HandlerDiscoveryResult();

        // Act
        var source = generator.GenerateOptimizedDispatcher(discoveryResult);

        // Assert
        Assert.Contains("public static class OptimizedDispatcher", source);
        Assert.DoesNotContain("public class OptimizedDispatcher", source); // Not non-static
    }

    [Fact]
    public void GenerateOptimizedDispatcher_ShouldIncludePerformanceOptimizationComments()
    {
        // Arrange
        var context = CreateTestContext();
        var generator = new OptimizedDispatcherGenerator(context);
        var discoveryResult = new HandlerDiscoveryResult();

        // Act
        var source = generator.GenerateOptimizedDispatcher(discoveryResult);

        // Assert
        Assert.Contains("High-performance dispatcher", source);
    }

    [Fact]
    public void GenerateOptimizedDispatcher_ShouldCloseAllBraces()
    {
        // Arrange
        var context = CreateTestContext();
        var generator = new OptimizedDispatcherGenerator(context);
        var discoveryResult = new HandlerDiscoveryResult();

        // Act
        var source = generator.GenerateOptimizedDispatcher(discoveryResult);

        // Assert
        var openBraces = source.Count(c => c == '{');
        var closeBraces = source.Count(c => c == '}');
        Assert.Equal(closeBraces, openBraces);
    }

    [Fact]
    public void GenerateOptimizedDispatcher_ShouldUseValueTask()
    {
        // Arrange
        var context = CreateTestContext();
        var generator = new OptimizedDispatcherGenerator(context);
        var discoveryResult = new HandlerDiscoveryResult();

        // Act
        var source = generator.GenerateOptimizedDispatcher(discoveryResult);

        // Assert
        // ValueTask is more efficient than Task for hot paths
        Assert.Contains("ValueTask", source);
    }

    [Fact]
    public void GenerateOptimizedDispatcher_ShouldGenerateWithConsistentFormatting()
    {
        // Arrange
        var context = CreateTestContext();
        var generator = new OptimizedDispatcherGenerator(context);
        var discoveryResult = new HandlerDiscoveryResult();

        // Act
        var source = generator.GenerateOptimizedDispatcher(discoveryResult);
        var lines = source.Split(new[] { "\r\n", "\r", "\n" }, StringSplitOptions.None);

        // Assert
        Assert.DoesNotContain("\r\n\r\n\r\n", source); // No triple newlines
        Assert.NotNull(lines);
    }

    [Fact]
    public void GenerateOptimizedDispatcher_ShouldGenerateCleanCode()
    {
        // Arrange
        var context = CreateTestContext();
        var generator = new OptimizedDispatcherGenerator(context);
        var discoveryResult = new HandlerDiscoveryResult();

        // Act
        var source = generator.GenerateOptimizedDispatcher(discoveryResult);

        // Assert - Check for clean code generation without checking compilation
        Assert.DoesNotContain("TODO", source);
        Assert.DoesNotContain("HACK", source);
        Assert.Contains("public static class OptimizedDispatcher", source);
    }

    [Fact]
    public void GenerateOptimizedDispatcher_WithSingleHandler_ShouldGenerateSpecializedMethod()
    {
        // Arrange
        var context = CreateTestContext();
        var generator = new OptimizedDispatcherGenerator(context);
        var discoveryResult = new HandlerDiscoveryResult();
        
        var handler = CreateMockHandler("TestRequest", "string", "TestHandler", "HandleAsync", false);
        discoveryResult.Handlers.Add(handler);

        // Act
        var source = generator.GenerateOptimizedDispatcher(discoveryResult);

        // Assert
        Assert.Contains("Dispatch_Test_TestRequest", source);
        Assert.Contains("Specialized dispatch method for Test.TestRequest", source);
        Assert.Contains("Direct invocation for single handler - maximum performance", source);
        Assert.Contains("serviceProvider.GetRequiredService<Test.TestHandler>()", source);
    }

    [Fact]
    public void GenerateOptimizedDispatcher_WithStaticHandler_ShouldGenerateStaticInvocation()
    {
        // Arrange
        var context = CreateTestContext();
        var generator = new OptimizedDispatcherGenerator(context);
        var discoveryResult = new HandlerDiscoveryResult();
        
        var handler = CreateMockHandler("TestRequest", "string", "TestHandler", "HandleAsync", true);
        discoveryResult.Handlers.Add(handler);

        // Act
        var source = generator.GenerateOptimizedDispatcher(discoveryResult);

        // Assert
        Assert.DoesNotContain("serviceProvider.GetRequiredService", source);
        Assert.Contains("Test.TestHandler.HandleAsync(request, cancellationToken)", source);
    }

    [Fact]
    public void GenerateOptimizedDispatcher_WithMultipleHandlers_ShouldGenerateSelectionLogic()
    {
        // Arrange
        var context = CreateTestContext();
        var generator = new OptimizedDispatcherGenerator(context);
        var discoveryResult = new HandlerDiscoveryResult();
        
        // Create two handlers with the same request type but different handler types
        var compilation = CreateCompilation(@"
namespace Test {
    public class TestRequest : Relay.Core.IRequest<string> { }
    public class TestHandler1 {
        public async System.Threading.Tasks.ValueTask<string> HandleAsync(TestRequest request, System.Threading.CancellationToken cancellationToken) => default;
    }
    public class TestHandler2 {
        public async System.Threading.Tasks.ValueTask<string> HandleAsync(TestRequest request, System.Threading.CancellationToken cancellationToken) => default;
    }
}");

        var semanticModel = compilation.GetSemanticModel(compilation.SyntaxTrees.First());
        var requestTypeSymbol = semanticModel.Compilation.GetTypeByMetadataName("Test.TestRequest");
        
        foreach (var handlerName in new[] { "TestHandler1", "TestHandler2" })
        {
            var handlerTypeSymbol = semanticModel.Compilation.GetTypeByMetadataName($"Test.{handlerName}");
            var methodSymbol = handlerTypeSymbol?.GetMembers("HandleAsync").OfType<IMethodSymbol>().FirstOrDefault();

            var handler = new HandlerInfo
            {
                MethodSymbol = methodSymbol,
                HandlerTypeSymbol = handlerTypeSymbol,
                RequestTypeSymbol = requestTypeSymbol,
                Attributes = new List<RelayAttributeInfo>
                {
                    new RelayAttributeInfo { Type = RelayAttributeType.Handle }
                }
            };
            
            discoveryResult.Handlers.Add(handler);
        }

        // Act
        var source = generator.GenerateOptimizedDispatcher(discoveryResult);

        // Assert
        Assert.Contains("Optimized handler selection with branch prediction", source);
        Assert.Contains("Most common handlers first for better branch prediction", source);
        Assert.Contains("No handler found with name", source);
    }

    [Fact]
    public void GenerateOptimizedDispatcher_WithVoidResponse_ShouldGenerateVoidMethod()
    {
        // Arrange
        var context = CreateTestContext();
        var generator = new OptimizedDispatcherGenerator(context);
        var discoveryResult = new HandlerDiscoveryResult();
        
        var handler = CreateMockHandler("TestRequest", "void", "TestHandler", "HandleAsync", false);
        discoveryResult.Handlers.Add(handler);

        // Act
        var source = generator.GenerateOptimizedDispatcher(discoveryResult);

        // Assert
        Assert.Contains("public static async ValueTask Dispatch_Test_TestRequest(", source);
        Assert.DoesNotContain("ValueTask<void>", source);
    }

    [Fact]
    public void GenerateOptimizedDispatcher_WithTypedResponse_ShouldGenerateTypedMethod()
    {
        // Arrange
        var context = CreateTestContext();
        var generator = new OptimizedDispatcherGenerator(context);
        var discoveryResult = new HandlerDiscoveryResult();
        
        var handler = CreateMockHandler("TestRequest", "string", "TestHandler", "HandleAsync", false);
        discoveryResult.Handlers.Add(handler);

        // Act
        var source = generator.GenerateOptimizedDispatcher(discoveryResult);

        // Assert
        Assert.Contains("public static async ValueTask<string> Dispatch_Test_TestRequest(", source);
    }

    [Fact]
    public void GenerateOptimizedDispatcher_WithStreamingHandlers_ShouldGenerateStreamingMethods()
    {
        // Arrange
        var context = CreateTestContext();
        var generator = new OptimizedDispatcherGenerator(context);
        var discoveryResult = new HandlerDiscoveryResult();
        
        // Create a mock streaming handler
        var compilation = CreateCompilation(@"
namespace Test {
    public class StreamRequest : Relay.Core.IStreamRequest<string> { }
    public class StreamHandler {
        public async System.Collections.Generic.IAsyncEnumerable<string> HandleAsync(StreamRequest request, System.Threading.CancellationToken cancellationToken) => default;
    }
}");

        var semanticModel = compilation.GetSemanticModel(compilation.SyntaxTrees.First());
        var requestTypeSymbol = semanticModel.Compilation.GetTypeByMetadataName("Test.StreamRequest");
        var handlerTypeSymbol = semanticModel.Compilation.GetTypeByMetadataName("Test.StreamHandler");
        var methodSymbol = handlerTypeSymbol?.GetMembers("HandleAsync").OfType<IMethodSymbol>().FirstOrDefault();

        var handler = new HandlerInfo
        {
            MethodSymbol = methodSymbol,
            HandlerTypeSymbol = handlerTypeSymbol,
            RequestTypeSymbol = requestTypeSymbol,
            Attributes = new List<RelayAttributeInfo>
            {
                new RelayAttributeInfo { Type = RelayAttributeType.Handle }
            }
        };
        
        discoveryResult.Handlers.Add(handler);

        // Act
        var source = generator.GenerateOptimizedDispatcher(discoveryResult);

        // Assert
        Assert.Contains("DispatchStreamAsync<TRequest, TResponse>", source);
        Assert.Contains("Optimized streaming dispatch method", source);
        Assert.Contains("IAsyncEnumerable<TResponse>", source);
        Assert.Contains("where TRequest : IStreamRequest<TResponse>", source);
    }

    [Fact]
    public void GenerateOptimizedDispatcher_WithNotificationHandlers_ShouldGenerateNotificationMethods()
    {
        // Arrange
        var context = CreateTestContext();
        var generator = new OptimizedDispatcherGenerator(context);
        var discoveryResult = new HandlerDiscoveryResult();
        
        // Create a mock notification handler
        var compilation = CreateCompilation(@"
namespace Test {
    public class TestNotification : Relay.Core.INotification { }
    public class NotificationHandler {
        public async System.Threading.Tasks.ValueTask HandleAsync(TestNotification notification, System.Threading.CancellationToken cancellationToken) => default;
    }
}");

        var semanticModel = compilation.GetSemanticModel(compilation.SyntaxTrees.First());
        var notificationTypeSymbol = semanticModel.Compilation.GetTypeByMetadataName("Test.TestNotification");
        var handlerTypeSymbol = semanticModel.Compilation.GetTypeByMetadataName("Test.NotificationHandler");
        var methodSymbol = handlerTypeSymbol?.GetMembers("HandleAsync").OfType<IMethodSymbol>().FirstOrDefault();

        var handler = new HandlerInfo
        {
            MethodSymbol = methodSymbol,
            HandlerTypeSymbol = handlerTypeSymbol,
            RequestTypeSymbol = notificationTypeSymbol,
            Attributes = new List<RelayAttributeInfo>
            {
                new RelayAttributeInfo { Type = RelayAttributeType.Notification }
            }
        };
        
        discoveryResult.Handlers.Add(handler);

        // Act
        var source = generator.GenerateOptimizedDispatcher(discoveryResult);

        // Assert
        Assert.Contains("DispatchNotificationAsync<TNotification>", source);
        Assert.Contains("Optimized notification dispatch method", source);
        Assert.Contains("where TNotification : INotification", source);
        Assert.Contains("var tasks = new List<ValueTask>()", source);
        Assert.Contains("ValueTask.WhenAll", source);
    }

    [Fact]
    public void GenerateOptimizedDispatcher_WithMainDispatchMethod_ShouldGenerateTypeSwitching()
    {
        // Arrange
        var context = CreateTestContext();
        var generator = new OptimizedDispatcherGenerator(context);
        var discoveryResult = new HandlerDiscoveryResult();
        
        var handler = CreateMockHandler("TestRequest", "string", "TestHandler", "HandleAsync", false);
        discoveryResult.Handlers.Add(handler);

        // Act
        var source = generator.GenerateOptimizedDispatcher(discoveryResult);

        // Assert
        Assert.Contains("DispatchAsync<TRequest, TResponse>", source);
        Assert.Contains("Main dispatch method with optimized type switching", source);
        Assert.Contains("Optimized type switching - most common types first", source);
        Assert.Contains("var requestType = typeof(TRequest)", source);
        Assert.Contains("if (requestType == typeof(Test.TestRequest))", source);
        Assert.Contains("await Dispatch_Test_TestRequest((Test.TestRequest)(object)request", source);
    }

    [Fact]
    public void GenerateOptimizedDispatcher_WithComplexTypeNames_ShouldSanitizeCorrectly()
    {
        // Arrange
        var context = CreateTestContext();
        var generator = new OptimizedDispatcherGenerator(context);
        var discoveryResult = new HandlerDiscoveryResult();
        
        // Create a handler with a complex type name
        var compilation = CreateCompilation(@"
namespace Test {
    public class ComplexRequest<T> : Relay.Core.IRequest<string> where T : class { }
    public class ComplexHandler {
        public async System.Threading.Tasks.ValueTask<string> HandleAsync(ComplexRequest<object> request, System.Threading.CancellationToken cancellationToken) => default;
    }
}");

        var semanticModel = compilation.GetSemanticModel(compilation.SyntaxTrees.First());
        var requestTypeSymbol = semanticModel.Compilation.GetTypeByMetadataName("Test.ComplexRequest`1")?.Construct(semanticModel.Compilation.GetSpecialType(SpecialType.System_Object));
        var handlerTypeSymbol = semanticModel.Compilation.GetTypeByMetadataName("Test.ComplexHandler");
        var methodSymbol = handlerTypeSymbol?.GetMembers("HandleAsync").OfType<IMethodSymbol>().FirstOrDefault();

        var handler = new HandlerInfo
        {
            MethodSymbol = methodSymbol,
            HandlerTypeSymbol = handlerTypeSymbol,
            RequestTypeSymbol = requestTypeSymbol,
            Attributes = new List<RelayAttributeInfo>
            {
                new RelayAttributeInfo { Type = RelayAttributeType.Handle }
            }
        };
        
        discoveryResult.Handlers.Add(handler);

        // Act
        var source = generator.GenerateOptimizedDispatcher(discoveryResult);

        // Assert
        Assert.Contains("Dispatch_Test_ComplexRequest_object_", source); // Sanitized method name
    }

    [Fact]
    public void GenerateOptimizedDispatcher_WithMultipleRequestTypes_ShouldGenerateMultipleMethods()
    {
        // Arrange
        var context = CreateTestContext();
        var generator = new OptimizedDispatcherGenerator(context);
        var discoveryResult = new HandlerDiscoveryResult();
        
        var handler1 = CreateMockHandler("Request1", "string", "Handler1", "HandleAsync", false);
        var handler2 = CreateMockHandler("Request2", "int", "Handler2", "HandleAsync", false);
        
        discoveryResult.Handlers.Add(handler1);
        discoveryResult.Handlers.Add(handler2);

        // Act
        var source = generator.GenerateOptimizedDispatcher(discoveryResult);

        // Assert
        Assert.Contains("Dispatch_Test_Request1", source);
        Assert.Contains("Dispatch_Test_Request2", source);
        Assert.Contains("ValueTask<string> Dispatch_Test_Request1(", source);
        Assert.Contains("ValueTask<int> Dispatch_Test_Request2(", source);
    }

    [Fact]
    public void GenerateOptimizedDispatcher_WithNoHandlers_ShouldGenerateBasicStructure()
    {
        // Arrange
        var context = CreateTestContext();
        var generator = new OptimizedDispatcherGenerator(context);
        var discoveryResult = new HandlerDiscoveryResult(); // Empty

        // Act
        var source = generator.GenerateOptimizedDispatcher(discoveryResult);

        // Assert
        Assert.Contains("public static class OptimizedDispatcher", source);
        Assert.DoesNotContain("Dispatch_", source);
        Assert.DoesNotContain("DispatchStreamAsync", source);
        Assert.DoesNotContain("DispatchNotificationAsync", source);
    }

    [Fact]
    public void GenerateOptimizedDispatcher_WithMixedHandlerTypes_ShouldGenerateAllMethods()
    {
        // Arrange
        var context = CreateTestContext();
        var generator = new OptimizedDispatcherGenerator(context);
        var discoveryResult = new HandlerDiscoveryResult();
        
        // Add regular handler
        var regularHandler = CreateMockHandler("RegularRequest", "string", "RegularHandler", "HandleAsync", false);
        discoveryResult.Handlers.Add(regularHandler);

        // Add streaming handler
        var compilation = CreateCompilation(@"
namespace Test {
    public class StreamRequest : Relay.Core.IStreamRequest<int> { }
    public class StreamHandler {
        public async System.Collections.Generic.IAsyncEnumerable<int> HandleAsync(StreamRequest request, System.Threading.CancellationToken cancellationToken) => default;
    }
}");
        var semanticModel = compilation.GetSemanticModel(compilation.SyntaxTrees.First());
        var streamRequestTypeSymbol = semanticModel.Compilation.GetTypeByMetadataName("Test.StreamRequest");
        var streamHandlerTypeSymbol = semanticModel.Compilation.GetTypeByMetadataName("Test.StreamHandler");
        var streamMethodSymbol = streamHandlerTypeSymbol?.GetMembers("HandleAsync").OfType<IMethodSymbol>().FirstOrDefault();

        var streamHandler = new HandlerInfo
        {
            MethodSymbol = streamMethodSymbol,
            HandlerTypeSymbol = streamHandlerTypeSymbol,
            RequestTypeSymbol = streamRequestTypeSymbol,
            Attributes = new List<RelayAttributeInfo>
            {
                new RelayAttributeInfo { Type = RelayAttributeType.Handle }
            }
        };
        discoveryResult.Handlers.Add(streamHandler);

        // Add notification handler
        var notificationCompilation = CreateCompilation(@"
namespace Test {
    public class TestNotification : Relay.Core.INotification { }
    public class NotificationHandler {
        public async System.Threading.Tasks.ValueTask HandleAsync(TestNotification notification, System.Threading.CancellationToken cancellationToken) => default;
    }
}");
        var notificationSemanticModel = notificationCompilation.GetSemanticModel(notificationCompilation.SyntaxTrees.First());
        var notificationTypeSymbol = notificationSemanticModel.Compilation.GetTypeByMetadataName("Test.TestNotification");
        var notificationHandlerTypeSymbol = notificationSemanticModel.Compilation.GetTypeByMetadataName("Test.NotificationHandler");
        var notificationMethodSymbol = notificationHandlerTypeSymbol?.GetMembers("HandleAsync").OfType<IMethodSymbol>().FirstOrDefault();

        var notificationHandler = new HandlerInfo
        {
            MethodSymbol = notificationMethodSymbol,
            HandlerTypeSymbol = notificationHandlerTypeSymbol,
            RequestTypeSymbol = notificationTypeSymbol,
            Attributes = new List<RelayAttributeInfo>
            {
                new RelayAttributeInfo { Type = RelayAttributeType.Notification }
            }
        };
        discoveryResult.Handlers.Add(notificationHandler);

        // Act
        var source = generator.GenerateOptimizedDispatcher(discoveryResult);

        // Assert
        Assert.Contains("Dispatch_Test_RegularRequest", source);
        Assert.Contains("DispatchStreamAsync", source);
        Assert.Contains("DispatchNotificationAsync", source);
        Assert.Contains("IAsyncEnumerable<TResponse>", source);
        Assert.Contains("where TRequest : IStreamRequest<TResponse>", source);
        Assert.Contains("where TNotification : INotification", source);
    }

    [Fact]
    public void GenerateOptimizedDispatcher_WithGenericTypeParameters_ShouldHandleCorrectly()
    {
        // Arrange
        var context = CreateTestContext();
        var generator = new OptimizedDispatcherGenerator(context);
        var discoveryResult = new HandlerDiscoveryResult();
        
        var handler = CreateMockHandler("GenericRequest", "List<string>", "GenericHandler", "HandleAsync", false);
        discoveryResult.Handlers.Add(handler);

        // Act
        var source = generator.GenerateOptimizedDispatcher(discoveryResult);

        // Assert
        Assert.Contains("ValueTask<List<string>> Dispatch_Test_GenericRequest(", source);
    }

    [Fact]
    public void GenerateOptimizedDispatcher_ShouldIncludeErrorHandlingForUnknownTypes()
    {
        // Arrange
        var context = CreateTestContext();
        var generator = new OptimizedDispatcherGenerator(context);
        var discoveryResult = new HandlerDiscoveryResult();
        
        var handler = CreateMockHandler("TestRequest", "string", "TestHandler", "HandleAsync", false);
        discoveryResult.Handlers.Add(handler);

        // Act
        var source = generator.GenerateOptimizedDispatcher(discoveryResult);

        // Assert
        Assert.Contains("No handler found for request type", source);
        // Note: "No handler found with name" only appears with multiple handlers
        // "No streaming handler found for request type" only appears with streaming handlers
    }

    [Fact]
    public void GenerateOptimizedDispatcher_ShouldUseAggressiveInlining()
    {
        // Arrange
        var context = CreateTestContext();
        var generator = new OptimizedDispatcherGenerator(context);
        var discoveryResult = new HandlerDiscoveryResult();
        
        var handler = CreateMockHandler("TestRequest", "string", "TestHandler", "HandleAsync", false);
        discoveryResult.Handlers.Add(handler);

        // Act
        var source = generator.GenerateOptimizedDispatcher(discoveryResult);

        // Assert
        var inlineCount = source.Split(new[] { "\r\n", "\r", "\n" }, StringSplitOptions.None)
            .Count(line => line.Contains("MethodImpl(MethodImplOptions.AggressiveInlining)"));
        
        Assert.True(inlineCount >= 2); // Should have at least 2 methods with inlining
    }

    [Fact]
    public void GenerateOptimizedDispatcher_WithMultipleNotificationHandlers_ShouldGenerateParallelExecution()
    {
        // Arrange
        var context = CreateTestContext();
        var generator = new OptimizedDispatcherGenerator(context);
        var discoveryResult = new HandlerDiscoveryResult();
        
        // Create multiple notification handlers for the same notification type
        var compilation = CreateCompilation(@"
namespace Test {
    public class TestNotification : Relay.Core.INotification { }
    public class NotificationHandler1 {
        public async System.Threading.Tasks.ValueTask HandleAsync(TestNotification notification, System.Threading.CancellationToken cancellationToken) => default;
    }
    public class NotificationHandler2 {
        public async System.Threading.Tasks.ValueTask HandleAsync(TestNotification notification, System.Threading.CancellationToken cancellationToken) => default;
    }
}");

        var semanticModel = compilation.GetSemanticModel(compilation.SyntaxTrees.First());
        var notificationTypeSymbol = semanticModel.Compilation.GetTypeByMetadataName("Test.TestNotification");
        
        foreach (var handlerName in new[] { "NotificationHandler1", "NotificationHandler2" })
        {
            var handlerTypeSymbol = semanticModel.Compilation.GetTypeByMetadataName($"Test.{handlerName}");
            var methodSymbol = handlerTypeSymbol?.GetMembers("HandleAsync").OfType<IMethodSymbol>().FirstOrDefault();

            var handler = new HandlerInfo
            {
                MethodSymbol = methodSymbol,
                HandlerTypeSymbol = handlerTypeSymbol,
                RequestTypeSymbol = notificationTypeSymbol,
                Attributes = new List<RelayAttributeInfo>
                {
                    new RelayAttributeInfo { Type = RelayAttributeType.Notification }
                }
            };
            
            discoveryResult.Handlers.Add(handler);
        }

        // Act
        var source = generator.GenerateOptimizedDispatcher(discoveryResult);

        // Assert
        Assert.Contains("var tasks = new List<ValueTask>()", source);
        Assert.Contains("ValueTask.WhenAll(tasks.ToArray())", source);
        Assert.Contains("NotificationHandler1", source);
        Assert.Contains("NotificationHandler2", source);
    }

    [Fact]
    public void GenerateOptimizedDispatcher_WithMultipleHandlers_ShouldIncludeErrorHandlingForUnknownHandlerNames()
    {
        // Arrange
        var context = CreateTestContext();
        var generator = new OptimizedDispatcherGenerator(context);
        var discoveryResult = new HandlerDiscoveryResult();
        
        var handler1 = CreateMockHandler("TestRequest", "string", "TestHandler1", "HandleAsync", false, "default", 1);
        var handler2 = CreateMockHandler("TestRequest", "string", "TestHandler2", "HandleAsync", false, "special", 2);
        
        discoveryResult.Handlers.Add(handler1);
        discoveryResult.Handlers.Add(handler2);

        // Act
        var source = generator.GenerateOptimizedDispatcher(discoveryResult);

        // Assert
        Assert.Contains("No handler found with name", source);
        Assert.Contains("Optimized handler selection with branch prediction", source);
    }
}
