using Microsoft.Extensions.DependencyInjection;
using Relay.Core.Contracts.Core;
using Relay.MinimalApiSample.Features.Products;
using Relay.MinimalApiSample.Infrastructure;
using Relay.MinimalApiSample.Models;
using Xunit;

public class ProductApiTests : IAsyncLifetime
{
    private IServiceProvider _serviceProvider;
    private IRelay _relay;
    private InMemoryDatabase _database;

    public async Task InitializeAsync()
    {
        var services = new ServiceCollection();

        // Register logging
        services.AddLogging();

        // Register sample services
        services.AddSingleton<IEmailService, ConsoleEmailService>();

        // Register Relay services (this will be generated by source generator in real app)
        services.AddRelay();

        // Register database after AddRelay to override the transient registration
        _database = new InMemoryDatabase(false); // Start with empty database for test isolation
        services.AddSingleton(_database);

        _serviceProvider = services.BuildServiceProvider();
        _relay = _serviceProvider.GetRequiredService<IRelay>();
    }

    public async Task DisposeAsync()
    {
        // Cleanup if needed
    }

    [Fact]
    public async Task GetAllProducts_WhenNoProductsExist_ReturnsEmptyList()
    {
        // Arrange - Clear database first
        _database.Clear();
        var request = new GetAllProductsRequest();

        // Act
        var response = await _relay.SendAsync(request);

        // Assert
        Assert.NotNull(response);
        Assert.Empty(response.Products);
    }

    [Fact]
    public async Task GetAllProducts_ReturnsProductsIncludingSeededData()
    {
        // Arrange - Ensure database has seeded data
        _database.Reseed();
        var request = new GetAllProductsRequest();

        // Act
        var response = await _relay.SendAsync(request);

        // Assert
        Assert.NotNull(response);
        Assert.NotEmpty(response.Products); // Database has seeded data
        Assert.True(response.Products.Count >= 2); // At least the seeded products
    }

    [Fact]
    public async Task CreateProduct_WithValidData_CreatesProductSuccessfully()
    {
        // Arrange
        var request = new CreateProductRequest("Test Product", "A test product description", 29.99m, 10);

        // Act
        var response = await _relay.SendAsync(request);

        // Assert
        Assert.NotNull(response);
        Assert.NotEqual(Guid.Empty, response.Id);
        Assert.Equal(request.Name, response.Name);
        Assert.Equal(request.Price, response.Price);

        // Verify product was added to database
        var product = _database.Products.FirstOrDefault(p => p.Value.Id == response.Id).Value;
        Assert.NotNull(product);
        Assert.Equal(request.Name, product.Name);
        Assert.Equal(request.Description, product.Description);
        Assert.Equal(request.Price, product.Price);
    }

    [Fact]
    public async Task GetProduct_WithValidId_ReturnsProduct()
    {
        // Arrange
        var createRequest = new CreateProductRequest("Premium Widget", "High-quality widget", 99.99m, 5);
        var createResponse = await _relay.SendAsync(createRequest);
        var productId = createResponse.Id;

        // Act
        var getRequest = new GetProductRequest(productId);
        var getResponse = await _relay.SendAsync(getRequest);

        // Assert
        Assert.NotNull(getResponse);
        Assert.Equal(productId, getResponse.Id);
        Assert.Equal(createRequest.Name, getResponse.Name);
        Assert.Equal(createRequest.Description, getResponse.Description);
        Assert.Equal(createRequest.Price, getResponse.Price);
    }

    [Fact]
    public async Task GetProduct_WithInvalidId_ReturnsNull()
    {
        // Arrange
        var invalidId = Guid.NewGuid();
        var request = new GetProductRequest(invalidId);

        // Act
        var response = await _relay.SendAsync(request);

        // Assert
        Assert.Null(response);
    }

    [Fact]
    public async Task CreateProduct_HandlesMultipleProductsCorrectly()
    {
        // Arrange - Clear database first to avoid seeded data interference
        _database.Clear();
        var products = new[]
        {
            new CreateProductRequest("Product A", "Desc A", 10.00m, 100),
            new CreateProductRequest("Product B", "Desc B", 20.00m, 200),
            new CreateProductRequest("Product C", "Desc C", 30.00m, 300)
        };

        // Act
        var responses = new List<CreateProductResponse>();
        foreach (var request in products)
        {
            var response = await _relay.SendAsync(request);
            responses.Add(response);
        }

        // Assert
        Assert.Equal(3, responses.Count);
        Assert.Equal(3, responses.Select(r => r.Id).Distinct().Count()); // All IDs unique

        // Verify all products in database
        var allProductsRequest = new GetAllProductsRequest();
        var allProductsResponse = await _relay.SendAsync(allProductsRequest);
        Assert.Equal(3, allProductsResponse.Products.Count);
    }

    [Fact]
    public async Task ProductOperations_AreIsolatedBetweenTests()
    {
        // This test verifies that each test runs in isolation
        // Arrange - Clear database first
        _database.Clear();
        var request = new GetAllProductsRequest();

        // Act
        var response = await _relay.SendAsync(request);

        // Assert
        // Database should be empty after clearing
        Assert.Empty(response.Products);
    }
}