using Microsoft.Extensions.DependencyInjection;
using Relay.Core.Contracts.Core;
using Relay.MinimalApiSample.Features.Users;
using Relay.MinimalApiSample.Infrastructure;
using Relay.MinimalApiSample.Models;
using Xunit;

public class UserApiTests : IAsyncLifetime
{
    private IServiceProvider _serviceProvider;
    private IRelay _relay;
    private InMemoryDatabase _database;

    public async Task InitializeAsync()
    {
        var services = new ServiceCollection();

        // Register logging
        services.AddLogging();

        // Register sample services
        services.AddSingleton<IEmailService, ConsoleEmailService>();

        // Register Relay services (this will be generated by source generator in real app)
        services.AddRelay();

        // Register database after AddRelay to override the transient registration
        _database = new InMemoryDatabase(false); // Start with empty database for test isolation
        services.AddSingleton(_database);

        _serviceProvider = services.BuildServiceProvider();
        _relay = _serviceProvider.GetRequiredService<IRelay>();
    }

    public async Task DisposeAsync()
    {
        // Cleanup if needed
    }

    [Fact]
    public async Task UserOperations_AreIsolatedBetweenTests()
    {
        // This test verifies that each test runs in isolation
        // Arrange - Clear database first
        _database.Clear();
        var request = new GetAllUsersRequest();

        // Act
        var response = await _relay.SendAsync(request);

        // Assert
        // Database should be empty after clearing
        Assert.Empty(response.Users);
    }

    [Fact]
    public async Task GetAllUsers_ReturnsUsersIncludingSeededData()
    {
        // Arrange - Ensure database has seeded data
        _database.Reseed();
        var request = new GetAllUsersRequest();

        // Act
        var response = await _relay.SendAsync(request);

        // Assert
        Assert.NotNull(response);
        Assert.NotEmpty(response.Users); // Database has seeded data
        Assert.True(response.Users.Count >= 2); // At least the seeded users
    }

    [Fact]
    public async Task CreateUser_WithValidData_CreatesUserSuccessfully()
    {
        // Arrange
        var request = new CreateUserRequest("John Doe", "john.doe@example.com");

        // Act
        var response = await _relay.SendAsync(request);

        // Assert
        Assert.NotNull(response);
        Assert.NotEqual(Guid.Empty, response.Id);
        Assert.Equal(request.Name, response.Name);
        Assert.Equal(request.Email, response.Email);

        // Verify user was added to database
        var user = _database.Users.FirstOrDefault(u => u.Value.Id == response.Id).Value;
        Assert.NotNull(user);
        Assert.Equal(request.Name, user.Name);
        Assert.Equal(request.Email, user.Email);
    }

    [Fact]
    public async Task GetUser_WithValidId_ReturnsUser()
    {
        // Arrange
        var createRequest = new CreateUserRequest("Jane Smith", "jane.smith@example.com");
        var createResponse = await _relay.SendAsync(createRequest);
        var userId = createResponse.Id;

        // Act
        var getRequest = new GetUserRequest(userId);
        var getResponse = await _relay.SendAsync(getRequest);

        // Assert
        Assert.NotNull(getResponse);
        Assert.Equal(userId, getResponse.Id);
        Assert.Equal(createRequest.Name, getResponse.Name);
        Assert.Equal(createRequest.Email, getResponse.Email);
    }

    [Fact]
    public async Task GetUser_WithInvalidId_ReturnsNull()
    {
        // Arrange
        var invalidId = Guid.NewGuid();
        var request = new GetUserRequest(invalidId);

        // Act
        var response = await _relay.SendAsync(request);

        // Assert
        Assert.Null(response);
    }

    [Fact]
    public async Task CreateUser_HandlesMultipleUsersCorrectly()
    {
        // Arrange - Clear database first to avoid seeded data interference
        _database.Clear();
        var users = new[]
        {
            new CreateUserRequest("User 1", "user1@example.com"),
            new CreateUserRequest("User 2", "user2@example.com"),
            new CreateUserRequest("User 3", "user3@example.com")
        };

        // Act
        var responses = new List<CreateUserResponse>();
        foreach (var request in users)
        {
            var response = await _relay.SendAsync(request);
            responses.Add(response);
        }

        // Assert
        Assert.Equal(3, responses.Count);
        Assert.Equal(3, responses.Select(r => r.Id).Distinct().Count()); // All IDs unique

        // Verify all users in database
        var allUsersRequest = new GetAllUsersRequest();
        var allUsersResponse = await _relay.SendAsync(allUsersRequest);
        Assert.Equal(3, allUsersResponse.Users.Count);
    }

    [Fact]
    public async Task UserOperations_AreIsolatedBetweenTests()
    {
        // This test verifies that each test runs in isolation
        // Arrange - Clear database first
        _database.Clear();
        var request = new GetAllUsersRequest();

        // Act
        var response = await _relay.SendAsync(request);

        // Assert
        // Database should be empty after clearing
        Assert.Empty(response.Users);
    }
}