name: Release

on:
  release:
    types: [published]

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish to NuGet
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Get release version
      id: get_version
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "Building version: $VERSION"
    
    - name: Restore dependencies
      run: dotnet restore Relay.sln
    
    - name: Build solution
      run: |
        dotnet build Relay.sln --no-restore --configuration Release \
          --verbosity minimal \
          -p:Version=${{ steps.get_version.outputs.VERSION }}
    
    - name: Run tests
      run: |
        dotnet test Relay.sln --no-build --configuration Release \
          --verbosity normal \
          --logger "console;verbosity=detailed"
    
    - name: Create NuGet packages
      run: |
        dotnet pack Relay.sln --no-build --configuration Release \
          --output ./artifacts \
          --verbosity minimal \
          -p:PackageVersion=${{ steps.get_version.outputs.VERSION }}
    
    - name: List packages
      run: |
        echo "Generated packages:"
        ls -la ./artifacts/
    
    - name: Publish to NuGet
      run: |
        dotnet nuget push ./artifacts/*.nupkg \
          --api-key ${{ secrets.NUGET_API_KEY }} \
          --source https://api.nuget.org/v3/index.json \
          --skip-duplicate \
          --no-symbols
    
    - name: Upload release artifacts
      uses: actions/upload-artifact@v5
      with:
        name: release-packages
        path: ./artifacts/*.nupkg
        retention-days: 90